image:
  repository: ghcr.io/linuxserver/proftpd
  tag: latest

service:
  port: 22
  targetPort: 2223
  LoadBalancerIP: "172.18.10.100"

persistence:
  enabled: true
  size: 5Gi

sftp:
  serverName: "ProFTPD Dev SFTP"