image:
  repository: atmoz/sftp
  tag: latest

service:
  externalPort: 2223
  containerPort: 22
  loadBalancerIP: "172.18.10.101"

persistence:
  enabled: true
  size: 5Gi

sftp:
  serverName: "ProFTPD Dev SFTP"
  users: "sftpuser:changeme:1000:1000:/home/sftp-data"