image:
  repository: ghcr.io/linuxserver/proftpd
  tag: latest

service:
  port: 2223
  targetPort: 22
  loadBalancerIP: "172.18.10.101"

persistence:
  enabled: true
  size: 5Gi

sftp:
  serverName: "ProFTPD Dev SFTP"