image:
  repository: ghcr.io/linuxserver/proftpd
  tag: latest

service:
  type: LoadBalancer
  port: 22
  targetPort: 22

persistence:
  enabled: true
  size: 5Gi

securityContext:
  runAsUser: 1000
  fsGroup: 1000

sftp:
  enabled: true
  serverName: "ProFTPD SFTP"
