image:
  repository: atmoz/sftp
  tag: latest

service:
  type: LoadBalancer
  port: 22
  targetPort: 22

persistence:
  enabled: true
  size: 5Gi

securityContext:
  runAsUser: 1000
  fsGroup: 1000

sftp:
  enabled: true
  users: "sftpuser:changeme:1000:1000:/home/sftp-data"
